# -*- encoding : utf-8 -*-
#
# configuration file for couchdbtools
#
app:
  logfile: './couchdbtools.log'
  loglevel: 0 # (DEBUG = 0) < (INFO = 1) < (WARN = 2) < (ERROR = 3) < (FATAL = 4) < (UNKNOWN = 5)
  log_date_time_format: '%Y-%m-%d %H:%M:%S'

db:
  host: 'localhost'
  name: 'kassenbuch'
  port: '5984'
  protocol: 'http'

